# Generated by Django 4.2.6 on 2024-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=20)),
                ('category_description', models.TextField(max_length=100)),
                ('category_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('feedback_title', models.CharField(max_length=50)),
                ('feedback_comment', models.CharField(max_length=100)),
                ('feedback_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('address_Line1', models.CharField(max_length=50)),
                ('address_Line2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('subtotal', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('order_status', models.CharField(max_length=30)),
                ('payment_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
