# Generated by Django 4.2.6 on 2024-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address_Line1', models.CharField(max_length=50)),
                ('address_Line2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
    ]
