# Generated by Django 4.2.6 on 2024-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_customer_pincode_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='disc_price',
        ),
        migrations.AddField(
            model_name='product',
            name='org_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True),
        ),
    ]
