# Generated by Django 4.2.6 on 2024-02-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_price_product_disc_price_product_org_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='org_price',
        ),
    ]
