# Generated by Django 4.2.6 on 2024-02-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_product_org_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disc_price',
            new_name='price',
        ),
    ]
