# Generated by Django 4.2.6 on 2024-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_disc_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.CharField(default='', max_length=20),
        ),
    ]
