# Generated by Django 4.2.6 on 2024-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_cart_imgage_alter_cart_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_Line1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_Line2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
